# The message prefix to run predefined shell commands (excluding `!`).
prefix_cmd: 'cmd'
# The list of user IDs who are allowed to execute predefined shell commands.
# There is absolutely no sandboxing in maubot or this plugin, keep this list small.
whitelist_cmd:
- '@user:example.com'
# Dict with predefined shell commands
# Key: command name (use `_` as placeholder for spaces ` ` in multi word commands)
# Value: command or shell script to execute
commands:
    ps: ps -ef | grep maubot
    device_off: echo powering off
    device_start: |
        echo device power on
        sleep 5
        echo device is starting
        sleep 5
        echo device started

# The message prefix to treat as exec commands (including `!`).
prefix_exec: '!exec'
# Whether or not to enable "userbot" mode, where commands that the bot's user
# sends are handled and responded to with edits instead of replies.
# This is intended to be used when you run the plugin on your own account.
userbot: false
# The list of user IDs who are allowed to execute stuff. There is absolutely no
# sandboxing in maubot or this plugin, keep this list small.
whitelist_exec: []

output:
    # Number of seconds to wait between output update edits.
    interval: 5
    # Arguments for the Jinja2 template initialization.
    template_args:
        lstrip_blocks: true
        trim_blocks: yes
    # Plaintext output template.
    plaintext: |
        Input ({{ input }}):
        {{ code }}
        {% if output %}

        Output:
        {{ output }}
        {% endif %}
        {% if return_value != None %}

        Return:
        {{ return_value }}
        {% endif %}
        {% if exception != None %}

        {% if exception_header %}{{ exception_header }}:{% endif %}
        {{ exception }}
        {% endif %}
        {% if duration != None %}

        Took {{ duration | round(3) }} seconds
        {% else %}

        Running...
        {% endif %}
    # HTML output template.
    html: |
        <h4>Input</h4>
        <pre><code class="language-{{ language }}">{{ code }}</code></pre>
        {% if output %}
        <h4>Output</h4>
        <pre>{{ output }}</pre>
        {% endif %}
        {% if return_value != None %}
            {% if language in ("bash", "sh", "shell") %}
            <h4>Return: <code>{{ return_value }}</code></h4>
            {% else %}
            <h4>Return</h4>
            <pre>{{ return_value }}</pre>
            {% endif %}
        {% endif %}
        {% if exception != None %}
            {% if exception_header %}<h4>{{ exception_header }}</h4>{% endif %}
            <pre><code class="language-pytb">{{ exception }}</code></pre>
        {% endif %}
        {% if duration != None %}
            <h4>Took {{ duration | round(3) }} seconds</h4>
        {% else %}
            <h4>Running...</h4>
        {% endif %}
